[package]
name = "nous"
version = "0.1.3-beta"
edition = "2024"
description = "lightweight and efficient web framework in Rust designed for handling HTTP requests with built-in gatekeeping middleware."
license = "MIT"

[dependencies]
flate2 = "1.1.0"
http-scrap = "0.1.1134"
quote = "1.0.38"
rusty-format = "0.1.4"
serde = "1.0.218"
serde_json = "1.0.139"
syn = { version = "2.0.98", features = ["full", "extra-traits"] }
rusty_gate = { version = "0.1.0" }
brotli = "7.0.0"
zstd = "0.13.3"
# tokio = { version = "1.43.0", features = ["full"] }
# tokio-tungstenite = "0.26.2"
